language: php
php:
  - 7.2
  - 7.1
  - 7.0
  - 5.5
install:
  - composer install --dev
  - mkdir -p build/logs
after_script:
  - CODECLIMATE_REPO_TOKEN=b7a829dc616aee388d971653073fb32f2a891c5720b9237f0921c5bc1257ea90 ./vendor/bin/test-reporter
